## Table 1

## Step 1: Setting up

In [27]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
}
page = requests.get(url, headers=headers)

soup = BeautifulSoup(page.text, 'html.parser')

In [4]:
#print(soup)

## Step 2: Getting the headers from the first table

In [5]:
table = soup.find_all('table')[0] #since its a list we can use indexing

In [6]:
titles = table.find_all('th') #using table instead of soup so we only pull from the first table. Soup will pull all the th from every table

In [7]:
titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD millions)
 </th>,
 <th>Revenue growth
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [8]:
table_titles = [headers.text.strip() for headers in titles]

print(table_titles)

['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [9]:
df = pd.DataFrame(columns  = table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

## Step 3: Getting the data from the td tags in the first table.

In [10]:
column_data = table.find_all('tr')

In [11]:
for row in column_data[1:]:  #starting from position 1 because position 0 is empty list[] which messes up the appending of data into the headers
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df) #checking the length of our data frame
    df.loc[length] = individual_row_data #appending each row of information into the next position in our data frame

In [12]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,Travelers,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical,"45,043",32.0%,"47,000","Indianapolis, Indiana"

## Step 4: Exporting to csv

In [51]:
df.to_csv(r'my-path\Companies.csv', index = False)

## Table 2

## Step 1: Getting headers from the second table

In [14]:
table2 = soup.find_all('table')[1]

In [15]:
headers2 = table2.find_all('th')

In [16]:
headers2

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD billions)
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [17]:
table2_headers = [header.text.strip() for header in headers2]
print(table2_headers)

['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters']

In [34]:
df2 = pd.DataFrame(columns = table2_headers)

In [35]:
df2

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

## Step 2: Getting the data from the td tags in the second table.

In [48]:
column_data2 = table2.find_all('tr')

In [53]:
for row in column_data2[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df2)
    df2.loc[length] = individual_row_data

In [54]:
df2

,Rank,Name,Industry,Revenue (USD billions),Employees,Headquarters
0,1,Cargill,Food & Drink,154,"155,000","Minnetonka, Minnesota"
1,2,Koch,Multicompany,125,"120,000","Wichita, Kansas"
2,3,Publix Super Markets,Food Markets,59.7,"260,000","Lakeland, Florida"
3,4,Mars,Food & Drink,55,"150,000","McLean, Virginia"
4,5,H-E-B Grocery Company,Food Markets,49.57,"175,000","San Antonio, Texas"
5,6,Reyes Holdings,"Food, Drink & Tobacco",44,"36,000","Rosemont, Illinois"
6,7,Enterprise Mobility,Services,38,"100,000","Clayton, Missouri"
7,8,Fidelity Investments,Insurance,32.7,"78,000","Boston, Massachusetts"
8,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25,"24,000","Miramar, Florida"
9,10,Cox Enterprises,Media,23.5,"50,000","Atlanta, Georgia"
10,1,Cargill,Food & Drink,154,"155,000","Minnetonka, Minnesota"
11,2,Koch,Multicompany,125,"120,000","Wichita, Kansas"
12,3,Publix Super Markets,Food Markets,59.7,"260,000","Lakeland, Florida"
13,4,Mars,Food & Drink,55,"150,000","McLean, Virginia"
14,5,H-E-B Grocery Company,Food Markets,49.57,"175,000","San Antonio, Texas"
15,6,Reyes Holdings,"Food, Drink & Tobacco",44,"36,000","Rosemont, Illinois"
16,7,Enterprise Mobility,Services,38,"100,000","Clayton, Missouri"
17,8,Fidelity Investments,Insurance,32.7,"78,000","Boston, Massachusetts"
18,9,Southern Glazer's Wine & Spirits,"Food, Drink & Tobacco",25,"24,000","Miramar, Florida"
19,10,Cox Enterprises,Media,23.5,"50,000","Atlanta, Georgia"

## Step 3: Exporting to csv

In [49]:
df2.to_csv(r'my-path\Private_Companies.csv', index = False)

## Table 3

## Step 1 : Getting headers from the third table

In [55]:
table3 = soup.find_all('table')[2]

In [80]:
headers3 = table3.find_all('th')

In [81]:
headers3

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Profits<br/>(USD millions)
 </th>,
 <th>Headquarters
 </th>]

In [82]:
table3_headers = [headers.text.strip() for headers in headers3]

In [83]:
print(table3_headers)

['Rank', 'Name', 'Industry', 'Profits(USD millions)', 'Headquarters']

In [84]:
df3 = pd.DataFrame(columns = table3_headers)

In [85]:
df3

Empty DataFrame
Columns: [Rank, Name, Industry, Profits(USD millions), Headquarters]
Index: []

## Step 2: Getting the data from the td tags in the second table.

In [86]:
column_data3 = table3.find_all('tr')

In [87]:
for row in column_data3[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]

    length = len(df3)
    df3.loc[length] = individual_row_data

In [88]:
df3

,Rank,Name,Industry,Profits(USD millions),Headquarters
0,1,Alphabet,Technology and cloud computing,"100,118","Mountain View, California"
1,2,Apple,Technology,"93,736","Cupertino, California"
2,3,Berkshire Hathaway,Conglomerate,"88,995","Omaha, Nebraska"
3,4,Microsoft,Technology and cloud computing,"88,136","Redmond, Washington"
4,5,Nvidia,Technology,"72,880","Santa Clara, California"
5,6,Meta Platforms,Technology,"62,360","Menlo Park, California"
6,7,Amazon,Retail and cloud computing,"59,248","Seattle, Washington"
7,8,JPMorgan Chase,Financials,"58,471","New York City, New York"
8,9,ExxonMobil,Petroleum industry,"33,680","Spring, Texas"
9,10,Bank of America,Financials,"27,132","Charlotte, North Carolina"

## Step 3: Exporting to csv

In [ ]:
df2.to_csv(r'my-path\Profit_Companies.csv', index = False)